<?php

namespace App\OpenApi;

/**
 * @OA\OpenApi(
 *   @OA\Info(title="Legacy API", version="1.0.0", description="Inventory API. Success responses use {success: true, data: ...}; errors use {success: false, error: {code, message, details?}}. Paginated lists place pagination metadata in meta.pagination."),
 *   @OA\Server(url="/", description="Current host"),
 *   @OA\Tag(name="Authentication"), @OA\Tag(name="Dashboard"),
 *   @OA\Tag(name="Products"), @OA\Tag(name="Categories"),
 *   @OA\Tag(name="Stock movements"),
 *   @OA\Components(
 *   @OA\Schema(schema="ApiSuccess", required={"success", "data"}, @OA\Property(property="success", type="boolean", example=true), @OA\Property(property="data", type="object"), @OA\Property(property="meta", type="object", nullable=true)),
 *   @OA\Schema(schema="ApiError", required={"success", "error"}, @OA\Property(property="success", type="boolean", example=false), @OA\Property(property="error", type="object", required={"code", "message"}, @OA\Property(property="code", type="string"), @OA\Property(property="message", type="string"), @OA\Property(property="details", type="object", nullable=true))),
 *   @OA\Schema(schema="LoginRequest", required={"email", "password"}, @OA\Property(property="email", type="string", format="email"), @OA\Property(property="password", type="string", format="password")),
 *   @OA\Schema(schema="LoginResponse", required={"token", "user"}, @OA\Property(property="token", type="string", description="Opaque token stored in users.api_token"), @OA\Property(property="user", type="object", @OA\Property(property="id", type="integer"), @OA\Property(property="name", type="string"), @OA\Property(property="email", type="string", format="email"))),
 *   @OA\Schema(schema="ProductInput", @OA\Property(property="name", type="string", description="Required when creating; update validation is not defined."), @OA\Property(property="description", type="string", nullable=true), @OA\Property(property="price", type="number", format="float", nullable=true), @OA\Property(property="stock", type="integer", nullable=true), @OA\Property(property="category_id", type="integer", nullable=true), @OA\Property(property="status", type="integer", nullable=true, description="Defaults to 1 on create.")),
 *   @OA\Schema(schema="CategoryInput", @OA\Property(property="name", type="string", description="Required when creating."), @OA\Property(property="description", type="string", nullable=true)),
 *   @OA\Schema(schema="StockMovementInput", @OA\Property(property="type", type="string", description="The literal 'salida' subtracts stock; every other value adds stock."), @OA\Property(property="quantity", type="integer"), @OA\Property(property="reason", type="string", nullable=true)),
 *   @OA\Schema(schema="Error", @OA\Property(property="message", type="string"))
 *   )
 * )
 *
 * @OA\Post(path="/api/login", tags={"Authentication"}, summary="Log in", security={}, @OA\RequestBody(required=true, @OA\JsonContent(ref="#/components/schemas/LoginRequest")), @OA\Response(response=200, description="Token and public user fields in data", @OA\JsonContent(ref="#/components/schemas/ApiSuccess")), @OA\Response(response=422, description="Invalid request", @OA\JsonContent(ref="#/components/schemas/ApiError")), @OA\Response(response=401, description="Invalid credentials", @OA\JsonContent(ref="#/components/schemas/ApiError")))
 * @OA\Get(path="/api/health", tags={"Dashboard"}, summary="Database health check", security={}, @OA\Response(response=200, description="Database query succeeded"), @OA\Response(response=500, description="Database query failed"))
 * @OA\Get(path="/api/me", tags={"Authentication"}, summary="Get authenticated user", security={{"LegacyTokenAuth":{}}}, @OA\Response(response=200, description="Raw user row; fields depend on database schema"), @OA\Response(response=401, description="Missing or invalid token"))
 * @OA\Post(path="/api/logout", tags={"Authentication"}, summary="Invalidate current token", security={{"LegacyTokenAuth":{}}}, @OA\Response(response=200, description="Token cleared"), @OA\Response(response=401, description="Missing or invalid token"))
 * @OA\Get(path="/api/dashboard", tags={"Dashboard"}, summary="Dashboard counters and records", security={{"LegacyTokenAuth":{}}}, @OA\Response(response=200, description="Counts, low-stock products, and up to 20 latest movements"), @OA\Response(response=401, description="Missing or invalid token"))
 * @OA\Get(path="/api/products", tags={"Products"}, summary="List products", security={{"LegacyTokenAuth":{}}}, @OA\Parameter(name="q", in="query", @OA\Schema(type="string"), description="Substring filter on name."), @OA\Parameter(name="category_id", in="query", @OA\Schema(type="integer")), @OA\Parameter(name="status", in="query", @OA\Schema(type="integer")), @OA\Parameter(name="min_price", in="query", @OA\Schema(type="number", minimum=0)), @OA\Parameter(name="max_price", in="query", @OA\Schema(type="number", minimum=0)), @OA\Parameter(name="min_stock", in="query", @OA\Schema(type="integer", minimum=0)), @OA\Parameter(name="max_stock", in="query", @OA\Schema(type="integer", minimum=0)), @OA\Parameter(name="sort_by", in="query", @OA\Schema(type="string", enum={"created_at", "name", "price", "stock"}, default="created_at")), @OA\Parameter(name="sort_direction", in="query", @OA\Schema(type="string", enum={"asc", "desc"}, default="desc")), @OA\Parameter(name="page", in="query", @OA\Schema(type="integer", minimum=1), description="Page number; defaults to 1."), @OA\Parameter(name="per_page", in="query", @OA\Schema(type="integer", minimum=1, maximum=100, default=15)), @OA\Response(response=200, description="Success envelope; product array in data and page details in meta.pagination", @OA\JsonContent(ref="#/components/schemas/ApiSuccess")), @OA\Response(response=401, description="Missing or invalid token", @OA\JsonContent(ref="#/components/schemas/ApiError")), @OA\Response(response=422, description="Validation error", @OA\JsonContent(ref="#/components/schemas/ApiError")))
 * @OA\Post(path="/api/products", tags={"Products"}, summary="Create product", security={{"LegacyTokenAuth":{}}}, @OA\RequestBody(required=true, @OA\JsonContent(ref="#/components/schemas/ProductInput")), @OA\Response(response=201, description="Created product"), @OA\Response(response=422, description="Missing name"))
 * @OA\Get(path="/api/products/{id}", tags={"Products"}, summary="Get product", security={{"LegacyTokenAuth":{}}}, @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")), @OA\Response(response=200, description="Product with category_name"), @OA\Response(response=404, description="Product not found"))
 * @OA\Put(path="/api/products/{id}", tags={"Products"}, summary="Update product", security={{"LegacyTokenAuth":{}}}, @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")), @OA\RequestBody(required=true, @OA\JsonContent(ref="#/components/schemas/ProductInput")), @OA\Response(response=200, description="Updated product"), @OA\Response(response=404, description="Product not found"))
 * @OA\Delete(path="/api/products/{id}", tags={"Products"}, summary="Delete product", security={{"LegacyTokenAuth":{}}}, @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")), @OA\Response(response=200, description="Deleted"), @OA\Response(response=404, description="Product not found"), @OA\Response(response=409, description="Product has stock movement history", @OA\JsonContent(ref="#/components/schemas/ApiError")))
 * @OA\Get(path="/api/products/{id}/stock-movements", tags={"Stock movements"}, summary="List product stock movements", security={{"LegacyTokenAuth":{}}}, @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")), @OA\Response(response=200, description="Success envelope containing the product movement history in data"), @OA\Response(response=404, description="Product not found", @OA\JsonContent(ref="#/components/schemas/ApiError")))
 * @OA\Post(path="/api/products/{id}/stock-movements", tags={"Stock movements"}, summary="Record stock movement", security={{"LegacyTokenAuth":{}}}, @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")), @OA\RequestBody(required=true, @OA\JsonContent(ref="#/components/schemas/StockMovementInput")), @OA\Response(response=200, description="Success envelope containing updated product and saved movement"), @OA\Response(response=404, description="Product not found", @OA\JsonContent(ref="#/components/schemas/ApiError")), @OA\Response(response=409, description="Insufficient stock for outgoing movement", @OA\JsonContent(ref="#/components/schemas/ApiError")), @OA\Response(response=422, description="Validation error", @OA\JsonContent(ref="#/components/schemas/ApiError")))
 * @OA\Get(path="/api/categories", tags={"Categories"}, summary="List categories", security={{"LegacyTokenAuth":{}}}, @OA\Parameter(name="q", in="query", @OA\Schema(type="string"), description="Substring filter on name."), @OA\Parameter(name="status", in="query", @OA\Schema(type="integer")), @OA\Parameter(name="sort_by", in="query", @OA\Schema(type="string", enum={"created_at", "name"}, default="created_at")), @OA\Parameter(name="sort_direction", in="query", @OA\Schema(type="string", enum={"asc", "desc"}, default="desc")), @OA\Parameter(name="page", in="query", @OA\Schema(type="integer", minimum=1), description="Page number; defaults to 1."), @OA\Parameter(name="per_page", in="query", @OA\Schema(type="integer", minimum=1, maximum=100, default=15)), @OA\Response(response=200, description="Success envelope; category array in data and page details in meta.pagination", @OA\JsonContent(ref="#/components/schemas/ApiSuccess")), @OA\Response(response=401, description="Missing or invalid token", @OA\JsonContent(ref="#/components/schemas/ApiError")), @OA\Response(response=422, description="Validation error", @OA\JsonContent(ref="#/components/schemas/ApiError")))
 * @OA\Post(path="/api/categories", tags={"Categories"}, summary="Create category", security={{"LegacyTokenAuth":{}}}, @OA\RequestBody(required=true, @OA\JsonContent(ref="#/components/schemas/CategoryInput")), @OA\Response(response=201, description="Created category"), @OA\Response(response=422, description="Missing name"))
 * @OA\Get(path="/api/categories/{id}", tags={"Categories"}, summary="Get category", security={{"LegacyTokenAuth":{}}}, @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")), @OA\Response(response=200, description="Category row or null when absent"))
 * @OA\Put(path="/api/categories/{id}", tags={"Categories"}, summary="Update category", security={{"LegacyTokenAuth":{}}}, @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")), @OA\RequestBody(required=true, @OA\JsonContent(ref="#/components/schemas/CategoryInput")), @OA\Response(response=200, description="Updated category"), @OA\Response(response=404, description="Category not found"))
 * @OA\Delete(path="/api/categories/{id}", tags={"Categories"}, summary="Delete category", security={{"LegacyTokenAuth":{}}}, @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")), @OA\Response(response=200, description="Deleted"), @OA\Response(response=404, description="Category not found"))
 */
final class ApiDocumentation
{
}
